#####################################
# Database Configuration
#####################################

# Name of database to use. Default is otrs.
otrsDbName: otrs

# Hostname or IP address of the database server. Default is mariadb.
otrsDbHost: my-db-mariadb

# Port of the database server. Default is 3306.
otrsDbPort: "3306"

# Database user. Default is otrs.
otrsDbUser: otrs

# otrs user database password. Default password is changeme
otrsDbPassword: changeme

# Database root user so it can be setup. Default user is root.
mysqlRootUser: root

# Database root password so it can be setup. Default password is changeme.
mysqlRootPassword: changeme

# Path to the docker secret file inside the container.
# otrsSecretsFile: ""

#####################################
# OTRS Configuration
#####################################

# Container startup mode, possible values:
#   - no      : Starts OTRS ready to be configured.
#   - yes     : Runs the OTRS installer.
#   - restore : Restores the backup specified by OTRS_BACKUP_DATE environment variable. Please check the README file for details.
otrsInstall: "no"

# otrsBackupDate: ""

# On backup restore it drops the otrs database it if already exists (by default the container will fail if the database already exists).
otrsDropDatabase: "no"

# Set the cron backup time. Default is to run daily at 6am.
# Set it to "disable" to disable automated backups
otrsBackupTime: 0 6 * * *

# Change the backup script that gets called from cron
otrsCronBackupScript: "/etc/cron.d/otrs_backup_custom"

# Change the article storage type (ArticleStorageDB|ArticleStorageFS). Default is ArticleStorageDB.
articleStorageType: ArticleStorageDB

# Set the backup type (fullbackup|nofullbackup|dbonly). Default is full backup.
otrsBackupType: fullbackup

# Set the backup compression method (gzip|bzip2). Default is gzip format.
otrsBackupCompression: gzip

# Set backup rotation days. Default is 30 days.
otrsBackupRotation: 10

# root@localhost user password. Default password is changeme
otrsRootPassword: changeme

# Sets the container's hostname (auto-generated if not defined).
otrsHostname: otrs.mycompany

# Set the default language for both agent and customer interfaces (For example, "es" for spanish).
otrsLanguage: en

# Sets the default timezone.
otrsTimezone: UTC

# Sets the starting point for the ticket counter.
# otrsTicketCounter: ""

# Sets the ticket number generator, possible values are : DateChecksum, Date, AutoIncrement or Random.
otrsNumberGenerator: DateChecksum

# Configure OTRS permissions, possible values are: yes (default), no, skip-article-dir (if using OTRS_ARTICLE_STORAGE_TYPE=ArticleStorageFS)
otrsSetPermissions: "yes"
#env-configmap
# To disable the OTRS ASCII logo at container startup.
showOtrsLogo: "yes"

# Enable debug mode, this will install some additional packages to help aid when
# debugging
otrsDebug: "no"

#Timezone /experimental/
# TZ: Etc/UTC

###### Major Version Upgrade #######
#####################################
# This settings will perform a major version upgrade. Please read the documentation
# carefully first before attempting to do this upgrade. And don't forget to do a
# backup first or enable OTRS_UPGRADE_BACKUP=yes
#
# https://github.com/juanluisbaptiste/docker-otrs/#major-version-upgrade
#
#####################################

# Do a MAJOR version upgrade. Possible values: yes, no (default). Please check the README file for details.
otrsUpgrade: "no"

# Make a full backup before starting the upgrade process. Possible values: yes (default), no.
otrsUpgradeBackup: "yes"

# Migrate XML configuration files during major version upgrade. Possible values: yes, no (default).
otrsUpgradeXmlFiles: "no"

#####################################
# SMTP Relay Configuration
#####################################

# Module OTRS should use to send mails (e.g "SMTP", "SMTPS", "Sendmail"). Depends on the modules you've installed
# otrsSendmailModule: SMTP

# Server address of the SMTP server to use.
# otrsSmtpServer:

# Port address of the SMTP server to use.
# otrsSmtpPort:

# Username to authenticate with.
# otrsSmtpUsername:

# Password of the SMTP user.
# otrsSmtpPassword:

#####################################
# Volume Claim properties
#####################################

#Kernel volume claim size
KernelStorage: 1Gi

#Skins volume claim size
skinsClaim: 100Mi

#Backup volume claim size
backupsClaim: 10Gi

#Addons volume claim size
addonsClaim: 100Mi

#DB upgrade volume claim size
db_upgradeClaim: 100Mi
