apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: otrs-dbupgradeclaim
  name: otrs-dbupgradeclaim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db_upgradeClaim }}
status: {}
