apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: otrs
  name: otrs
spec:
  selector:
    matchLabels:
      io.kompose.service: otrs
  serviceName: "otrs"
  replicas: 1
  template:
    metadata:
      annotations:
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: otrs
    spec:
      containers:
      - name: otrs
        envFrom:
          - configMapRef:
              name: configmap-otrs
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /opt/otrs/Kernel
          name: otrs-kernelclaim
          subPath: Kernel
        - mountPath: /opt/otrs/var/httpd/htdocs/skins/
          name: otrs-skinsclaim
        - mountPath: /var/otrs/backups
          name: otrs-backupsclaim
        - mountPath: /opt/otrs/addons
          name: otrs-addonsclaim
        - mountPath: /opt/otrs/db_upgrade
          name: otrs-dbupgradeclaim
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: otrs-kernelclaim
        persistentVolumeClaim:
          claimName: otrs-kernelclaim
      - name: otrs-skinsclaim
        persistentVolumeClaim:
          claimName: otrs-skinsclaim
      - name: otrs-backupsclaim
        persistentVolumeClaim:
          claimName: otrs-backupsclaim
      - name: otrs-addonsclaim
        persistentVolumeClaim:
          claimName: otrs-addonsclaim
      - name: otrs-dbupgradeclaim
        persistentVolumeClaim:
          claimName: otrs-dbupgradeclaim
status:
  replicas: 1
