apiVersion: v1
name: helm-otrs
version: 0.1
description: postfix helm chart for otrs
sources:
    - juanluisbaptiste/docker-postfix
maintainers:
  - name: rkeri
  - url: rkeri/helm-otrs
appVersion: 1.0
