apiVersion: v1
kind: Service
metadata:
  name: otrs
  labels:
    io.kompose.service: otrs
  annotations:
    kompose.version: 1.21.0 (992df58d8)
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: otrs
status:
  loadBalancer: {}
