apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: otrs
  name: otrs
spec:
  # replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otrs
  serviceName: "otrs"
  replicas: 1
  # strategy:
  #   type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: otrs
    spec:
      containers:
      - name: otrs
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.mysqlRootPassword }}"
        - name: MYSQL_ROOT_USER
          value: "{{ .Values.mysqlRootUser }}"
        - name: OTRS_ARTICLE_STORAGE_TYPE
          value: "{{ .Values.articleStorageType }}"
        - name: OTRS_BACKUP_COMRESSION
          value: "{{ .Values.otrsBackupCompression }}"
        - name: OTRS_BACKUP_DATE
          value: "{{ .Values.otrsBackupDate }}"
        - name: OTRS_BACKUP_ROTATION
          value: "{{ .Values.otrsBackupRotation }}"
        - name: OTRS_BACKUP_TIME
          value: "{{ .Values.otrsBackupTime }}"
        - name: OTRS_BACKUP_TYPE
          value: "{{ .Values.otrsBackupType }}"
        - name: OTRS_CRON_BACKUP_SCRIPT
          value: "{{ .Values.otrsCronBackupScript }}"
        - name: OTRS_DB_HOST
          value: "{{ .Values.otrsDbHost }}"
        - name: OTRS_DB_NAME
          value: "{{ .Values.otrsDbName }}"
        - name: OTRS_DB_PASSWORD
          value: "{{ .Values.otrsDbPassword }}"
        - name: OTRS_DB_PORT
          value: "{{ .Values.otrsDbPort }}"
        - name: OTRS_DB_USER
          value: "{{ .Values.otrsDbUser }}"
        - name: OTRS_DEBUG
          value: "{{ .Values.otrsDebug }}"
        - name: OTRS_DROP_DATABASE
          value: "{{ .Values.otrsDropDatabase }}"
        - name: OTRS_HOSTNAME
          value: "{{ .Values.otrsHostname }}"
        - name: OTRS_INSTALL
          value: "{{ .Values.otrsInstall }}"
        - name: OTRS_LANGUAGE
          value: "{{ .Values.otrsLanguage }}"
        - name: OTRS_NUMBER_GENERATOR
          value: "{{ .Values.otrsNumberGenerator }}"
        - name: OTRS_ROOT_PASSWORD
          value: "{{ .Values.otrsRootPassword }}"
        - name: OTRS_SECRETS_FILE
          value: "{{ .Values.otrsSecretsFile }}"
        - name: OTRS_SENDMAIL_MODULE
          value: "{{ .Values.otrsSendmailModule }}"
        - name: OTRS_SET_PERMISSIONS
          value: "{{ .Values.otrsSetPermissions }}"
        - name: OTRS_SMTP_PASSWORD
          value: "{{ .Values.otrsSmtpPassword }}"
        - name: OTRS_SMTP_PORT
          value: "{{ .Values.otrsSmtpPort }}"
        - name: OTRS_SMTP_SERVER
          value: "{{ .Values.otrsSmtpServer }}"
        - name: OTRS_SMTP_USERNAME
          value: "{{ .Values.otrsSmtpUsername }}"
        - name: OTRS_TICKET_COUNTER
          value: "{{ .Values.otrsTicketCounter }}"
        - name: OTRS_TIMEZONE
          value: "{{ .Values.otrsTimezone }}"
        - name: OTRS_UPGRADE
          value: "{{ .Values.otrsUpgrade }}"
        - name: OTRS_UPGRADE_BACKUP
          value: "{{ .Values.otrsUpgradeBackup }}"
        - name: OTRS_UPGRADE_XML_FILES
          value: "{{ .Values.otrsUpgradeXmlFiles }}"
        - name: SHOW_OTRS_LOGO
          value: "{{ .Values.showOtrsLogo }}"
        - name: TZ
          value: {{ .Values.TZ }}
        image: juanluisbaptiste/otrs:6.0.28
        imagePullPolicy: ""
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /opt/otrs/Kernel
          name: otrs-kernelclaim
          subPath: Kernel
        - mountPath: /opt/otrs/var/httpd/htdocs/skins/
          name: otrs-skinsclaim
        - mountPath: /var/otrs/backups
          name: otrs-backupsclaim
        - mountPath: /opt/otrs/addons
          name: otrs-addonsclaim
        - mountPath: /opt/otrs/db_upgrade
          name: otrs-dbupgradeclaim
        # - mountPath: /etc/localtime
        #   name: otrs-hostpath0
        #   readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: otrs-kernelclaim
        persistentVolumeClaim:
          claimName: otrs-kernelclaim
      - name: otrs-skinsclaim
        persistentVolumeClaim:
          claimName: otrs-skinsclaim
      - name: otrs-backupsclaim
        persistentVolumeClaim:
          claimName: otrs-backupsclaim
      - name: otrs-addonsclaim
        persistentVolumeClaim:
          claimName: otrs-addonsclaim
      - name: otrs-dbupgradeclaim
        persistentVolumeClaim:
          claimName: otrs-dbupgradeclaim
      # - name: otrs-hostpath0
      #   hostPath:
      #     path: /etc/localtime
      #     type: File
      # - hostPath:
      #     path: /etc/localtime
      #     type: File
      #   name: otrs-hostpath0
status:
  replicas: 1
