apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: otrs
  name: otrs
spec:
  # replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otrs
  serviceName: "otrs"
  replicas: 1
  # strategy:
  #   type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: otrs
    spec:
      containers:
      - name: otrs
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: env
        - name: MYSQL_ROOT_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_USER
              name: env
        - name: OTRS_ARTICLE_STORAGE_TYPE
          valueFrom:
            configMapKeyRef:
              key: OTRS_ARTICLE_STORAGE_TYPE
              name: env
        - name: OTRS_BACKUP_COMRESSION
          valueFrom:
            configMapKeyRef:
              key: OTRS_BACKUP_COMRESSION
              name: env
        - name: OTRS_BACKUP_DATE
          valueFrom:
            configMapKeyRef:
              key: OTRS_BACKUP_DATE
              name: env
        - name: OTRS_BACKUP_ROTATION
          valueFrom:
            configMapKeyRef:
              key: OTRS_BACKUP_ROTATION
              name: env
        - name: OTRS_BACKUP_TIME
          valueFrom:
            configMapKeyRef:
              key: OTRS_BACKUP_TIME
              name: env
        - name: OTRS_BACKUP_TYPE
          valueFrom:
            configMapKeyRef:
              key: OTRS_BACKUP_TYPE
              name: env
        - name: OTRS_CRON_BACKUP_SCRIPT
          valueFrom:
            configMapKeyRef:
              key: OTRS_CRON_BACKUP_SCRIPT
              name: env
        - name: OTRS_DB_HOST
          valueFrom:
            configMapKeyRef:
              key: OTRS_DB_HOST
              name: env
        - name: OTRS_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: OTRS_DB_NAME
              name: env
        - name: OTRS_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: OTRS_DB_PASSWORD
              name: env
        - name: OTRS_DB_PORT
          valueFrom:
            configMapKeyRef:
              key: OTRS_DB_PORT
              name: env
        - name: OTRS_DB_USER
          valueFrom:
            configMapKeyRef:
              key: OTRS_DB_USER
              name: env
        - name: OTRS_DEBUG
          valueFrom:
            configMapKeyRef:
              key: OTRS_DEBUG
              name: env
        - name: OTRS_DROP_DATABASE
          valueFrom:
            configMapKeyRef:
              key: OTRS_DROP_DATABASE
              name: env
        - name: OTRS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: OTRS_HOSTNAME
              name: env
        - name: OTRS_INSTALL
          valueFrom:
            configMapKeyRef:
              key: OTRS_INSTALL
              name: env
        - name: OTRS_LANGUAGE
          valueFrom:
            configMapKeyRef:
              key: OTRS_LANGUAGE
              name: env
        - name: OTRS_NUMBER_GENERATOR
          valueFrom:
            configMapKeyRef:
              key: OTRS_NUMBER_GENERATOR
              name: env
        - name: OTRS_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: OTRS_ROOT_PASSWORD
              name: env
        - name: OTRS_SECRETS_FILE
          valueFrom:
            configMapKeyRef:
              key: OTRS_SECRETS_FILE
              name: env
        - name: OTRS_SENDMAIL_MODULE
          valueFrom:
            configMapKeyRef:
              key: OTRS_SENDMAIL_MODULE
              name: env
        - name: OTRS_SET_PERMISSIONS
          valueFrom:
            configMapKeyRef:
              key: OTRS_SET_PERMISSIONS
              name: env
        - name: OTRS_SMTP_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: OTRS_SMTP_PASSWORD
              name: env
        - name: OTRS_SMTP_PORT
          valueFrom:
            configMapKeyRef:
              key: OTRS_SMTP_PORT
              name: env
        - name: OTRS_SMTP_SERVER
          valueFrom:
            configMapKeyRef:
              key: OTRS_SMTP_SERVER
              name: env
        - name: OTRS_SMTP_USERNAME
          valueFrom:
            configMapKeyRef:
              key: OTRS_SMTP_USERNAME
              name: env
        - name: OTRS_TICKET_COUNTER
          valueFrom:
            configMapKeyRef:
              key: OTRS_TICKET_COUNTER
              name: env
        - name: OTRS_TIMEZONE
          valueFrom:
            configMapKeyRef:
              key: OTRS_TIMEZONE
              name: env
        - name: OTRS_UPGRADE
          valueFrom:
            configMapKeyRef:
              key: OTRS_UPGRADE
              name: env
        - name: OTRS_UPGRADE_BACKUP
          valueFrom:
            configMapKeyRef:
              key: OTRS_UPGRADE_BACKUP
              name: env
        - name: OTRS_UPGRADE_XML_FILES
          valueFrom:
            configMapKeyRef:
              key: OTRS_UPGRADE_XML_FILES
              name: env
        - name: SHOW_OTRS_LOGO
          valueFrom:
            configMapKeyRef:
              key: SHOW_OTRS_LOGO
              name: env
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: env
        image: juanluisbaptiste/otrs:6.0.28
        imagePullPolicy: ""
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /opt/otrs/Kernel
          name: otrs-Kernel
          subPath: Kernel
        - mountPath: /opt/otrs/var/httpd/htdocs/skins/
          name: otrs-skins
        - mountPath: /var/otrs/backups
          name: otrs-backups
        - mountPath: /opt/otrs/addons
          name: otrs-addons
        - mountPath: /opt/otrs/db_upgrade
          name: otrs-db_upgrade
        # - mountPath: /etc/localtime
        #   name: otrs-hostpath0
        #   readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: otrs-Kernel
        persistentVolumeClaim:
          claimName: otrs-KernelClaim
      - name: otrs-skins
        persistentVolumeClaim:
          claimName: otrs-skinsClaim
      - name: otrs-backups
        persistentVolumeClaim:
          claimName: otrs-backupsClaim
      - name: otrs-addons
        persistentVolumeClaim:
          claimName: otrs-addonsClaim
      - name: otrs-db_upgrade
        persistentVolumeClaim:
          claimName: otrs-db_upgradeClaim
      # - name: otrs-hostpath0
      #   hostPath:
      #     path: /etc/localtime
      #     type: File
      # - hostPath:
      #     path: /etc/localtime
      #     type: File
      #   name: otrs-hostpath0
status:
  replicas: 1
